services:
  database:
    container_name: "postgres-dev-course"
    image: "postgres:14"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5490:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
